
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

// Workaround for TypeScript errors - a more complete Database type should be generated
// using Supabase CLI's `supabase gen types typescript` command
export type Database = {
  public: {
    Tables: {
      // Define the plans table explicitly
      plans: {
        Row: {
          app_name: string | null;
          branding: any | null; // Using any for Json type
          company_name: string | null;
          created_at: string | null;
          estimated_cost: number | null;
          estimated_days: number | null;
          features: string[] | null;
          id: string;
          status: string | null;
          username: string;
        };
        Insert: {
          app_name?: string | null;
          branding?: any | null;
          company_name?: string | null;
          created_at?: string | null;
          estimated_cost?: number | null;
          estimated_days?: number | null;
          features?: string[] | null;
          id?: string;
          status?: string | null;
          username: string;
        };
        Update: {
          app_name?: string | null;
          branding?: any | null;
          company_name?: string | null;
          created_at?: string | null;
          estimated_cost?: number | null;
          estimated_days?: number | null;
          features?: string[] | null;
          id?: string;
          status?: string | null;
          username?: string;
        };
        Relationships: [];
      };
      // Allow access to any other table (temporarily until proper types are generated)
      [tableName: string]: {
        Row: any;
        Insert: any;
        Update: any;
        Relationships: any[];
      };
    };
    Views: {};
    Functions: {};
    Enums: {};
    CompositeTypes: {};
  };
};

const SUPABASE_URL = "https://avdgyrepwrvsvwgxrccr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF2ZGd5cmVwd3J2c3Z3Z3hyY2NyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM2MzgwODIsImV4cCI6MjA1OTIxNDA4Mn0.8MZ2etAhQ1pTJnK84uoqAFfUirv_kaoYcmKHhKgLAWU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Type assertion helper for typed queries to any table
export function typedQuery<T>(table: string) {
  return supabase.from(table) as unknown as T;
}
